### ISSUE TITLE
Source /var/tmp/ansible-tmp-1576815212.99-239818871633791/source not found in /opt/ansible/roles/splunk_common/tasks/set_config_file.yml

### ISSUE THREAD

**Issue by azilbersteinSFDC** [splunk/splunk-ansible#334] opened 2019-12-20 04:31 UTC
Hi,

I'm trying to stand up a Splunk cluster using the Docker image.
Locally, on my Mac, I am able to use a docker-compose file to stand up a cluster with 8 containers (1 clustermaster, 1 licensemaster, 3 searchheads and 3 indexers).

When trying to deploy the same on an AWS host, the `docker run` command fails with this:
```
TASK [splunk_common : Create /opt/splunk/etc/system/local directory if not existing] ***
task path: /opt/ansible/roles/splunk_common/tasks/set_config_file.yml:2
ok: [localhost] => {
    "changed": false,
    "gid": 41812,
    "group": "splunk",
    "mode": "0755",
    "owner": "splunk",
    "path": "/opt/splunk/etc/system/local",
    "size": 4096,
    "state": "directory",
    "uid": 41812
}
Friday 20 December 2019  04:13:32 +0000 (0:00:00.216)       0:00:12.354 *******

TASK [splunk_common : Create props.conf if not existing] ***********************
task path: /opt/ansible/roles/splunk_common/tasks/set_config_file.yml:10
fatal: [localhost]: FAILED! => {
    "changed": false,
    "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
}

MSG:

Source /var/tmp/ansible-tmp-1576815212.99-239818871633791/source not found
```

In my setup I am mounting both `/opt/splunk/var` and `/opt/splunk/etc` to the host file system. I've verified that the directories are fully accessible - even chmod'ed them to 777.

I'm getting this error on my first execution of `docker run`, when the folders are empty. On subsequent executions, there is no error. But looking into the folders, the configuration files that should have been created in `/opt/splunk/etc/system/local` were not created. I have specified some custom configuration in my `default.yml` that is supposed to create the config files (and it does work on my local).

The same problem reproduces in 8.0.0 and 7.3.3. I tried using an older version that did not seem to have the problem, but the config files were not created either there, even on my local. So reverting is not an option.

If it makes any difference, I am wrapping the Splunk Docker image with my own. This is because my system does not allow hosts to pull Docker images from the internet. My Dockerfile is basically this:
```
FROM splunk/splunk:8.0.0

COPY license.xml /splunk-license.xml
COPY default.yml /tmp/defaults/default.yml
```
and I supply the files locally.

I've run out of ideas and would welcome any thought. Also, I noticed that a similar issue was resolved before - https://github.com/splunk/docker-splunk/issues/228 - same error message but on a different step. I hope this can shed some light into the issue.

Please let me know if you need more information.

**Comment by azilbersteinSFDC** [comment] 2019-12-20 08:57
So after looking at this in more depth I found out a workaround. 

In line https://github.com/splunk/splunk-ansible/blob/8.0.0/roles/splunk_common/tasks/set_config_file.yml#L16 we have `content: ""` which is trying to create an empty file. I suspect that Ansible is not creating the file at all in this case.

So I modified the `set_config.yml` file where the empty content string is defined to have some non-empty string `content: "# config file."` and following this fix Ansible was creating this file, generating all the files in `/opt/splunk/etc/system/local` as expected and continuing to success.

Should I create a pull request for this fix? Is there anyone else seeing this problem?

**Comment by nwang92** [comment] 2020-01-02 18:08
I believe we did notice this problem manifesting in other areas, although I'm not quite sure what the root cause was. The alternative we found was to switch from the `copy` module to the `file` module ala https://github.com/splunk/splunk-ansible/pull/255/files.

I wasn't aware this was in the `set_config_file.yml` playbook, but I can shoot a quick PR to address this.

**Comment by nwang92** [comment] 2020-01-02 23:41
Fixed in the above PR - this should be available in our next round of image releases (although I'm not too sure of ETA as of yet).

**Closed by nwang92** 2020-01-02 23:41 UTC

**Comment by azilbersteinSFDC** [comment] 2020-01-03 01:16
Thanks @nwang92 ! I'll check this change on my local once this change is incorporated into a new version of Splunk Docker image.
