### ISSUE TITLE
S2S/HEC enabled on indexer before first bundle causes data loss

### ISSUE THREAD

**Issue by mikedickey** [splunk/splunk-ansible#439] opened 2020-04-10 22:06 UTC
From @rfaircloth-splunk 

The current deployment uses ansible to enable inputs in etc/system/local this is dangerous because when scaling or simply a race condition the indexer will not be aware of its indexes and data will be lost when in an indexer cluster no more should be configured than is required to join the cluster. The master apps folder must be used to push inputs.conf

**Comment by mikedickey** [comment] 2020-04-10 22:07
Seems we should just be able to update plays to do this before splunk is first started?

**Comment by nwang92** [comment] 2020-05-19 20:34
S2S has been moved to execute before Splunk starts.

For HEC, this seems to be a duplicate of https://github.com/splunk/splunk-ansible/issues/291. I'm wondering/questioning if HEC is even worth doing here. The `splunk.hec.*` settings are mainly intended for short-lived deployments and accessibility with respect to getting data in quickly. But for any real workload, you're probably not using this to manage your HEC inputs.

A real customer is probably running more than a single HEC input, which is already outside of the capability of what `splunk.hec.*` provides. These HEC inputs can then be packaged as an app and installed through the cluster master/distributed to indexers using those provisioning hooks.

Maybe this should just be a documentation change to discourage `splunk.hec.*` for production deployments?

**Comment by mikedickey** [comment] 2020-05-19 20:55
On k8s at least, I'm pretty sure that indexer pods would not be added to the service until they are "ready" which currently requires completion of all the plays. I haven't looked closely at this; do we know that indexers will receive the bundle push from cluster master, or is it possible for that to complete afterwards?

**Comment by nwang92** [comment] 2020-05-20 04:08
> On k8s at least, I'm pretty sure that indexer pods would not be added to the service until they are "ready" which currently requires completion of all the plays.

I think that would depend on what the readiness probe configured is set as. The docker image ships with a [healthcheck script enabled](https://github.com/splunk/docker-splunk/blob/develop/splunk/common-files/Dockerfile#L115), but I don't know if that translates automatically into a readiness probe when used in k8s. 

I think there are two cases that would occur:
* Indexer plays complete **before** `splunk apply cluster-bundle` is executed on the master - due to the distributed nature of the provisioning, the indexer wouldn't know that there is an incoming bundle
* Indexer plays complete **during/after** `splunk apply cluster-bundle` is executed on the master - I don't think we wait now, but there may be an API we can query to do some busy-waiting?

While we may to able to fix the second case, I'm not sure how to approach the first situation. Even busy-waiting might have some pitfalls - some apps like ESS are not only large in size, but also require Splunk to be running in order to install + run the setup scripts necessary to pull down dependencies. 

Overall the app installation process is very container-native and it's a bit of a chore to reconcile some of these differences :) I wonder how much data loss there really is in situations like this. Presumably a user would not send data directly to an indexer but instead to some forwarder tier. Maybe as indexers are getting setup the forwarder would either backoff shipping logs or possibly even queue it?

**Comment by mikedickey** [comment] 2020-05-20 20:57
I think the case of cluster creation is probably unique and rare enough to not be an issue. @rfaircloth-splunk let me know if you disagree but I believe the problem here is really with what happens when new peers are added to the cluster.

Looking at [docs](https://docs.splunk.com/Documentation/Splunk/8.0.1/Indexer/Updatepeerconfigurations#Distribution_of_the_bundle_when_a_peer_starts_up):

> After you initially configure a Splunk instance as a peer node, you must restart it manually in order for it to join the cluster, as described in Enable the peer nodes. During this restart, the peer connects with the master, downloads the current configuration bundle, validates the bundle locally, and then restarts again. The peer only joins the cluster if bundle validation succeeds. This same process also occurs when an offline peer comes back online.

This seems to suggest it is not an issue because a new peer will not come online until after it gets the latest bundle from the master. The plays are handling the registration and subsequent restarts, so it seems they guarantee the peer will have the latest config bundle when they complete. In k8s, a peer isn't marked "ready" until they complete, and they aren't added to a service/LB until after they are ready.

**Comment by nwang92** [comment] 2021-03-03 04:54
Going to close this since S2S is addressed and the built-in HEC option is more geared towards faster GDI. For full deployments, apps can include HEC settings in an `inputs.conf` which will go through proper installation/bundle replication procedures.

**Closed by nwang92** 2021-03-03 04:54 UTC
Labels: A380
