### ISSUE TITLE
splunk_deployment_server forces all apps to be installed as apps on the server.

### ISSUE THREAD

**Issue by sharkannon** [splunk/splunk-ansible#158] opened 2019-04-12 22:41 UTC
I'm trying to setup a distributed environment.  Currently we're running splunk 7.2.3 using the old style docker containers, but I'm trying to move to the the configuration.

I've started with our deployment server (since it's the least impacting server).  Below is what I execute to create the deployment_server
```
docker run -it \
  -e SPLUNK_START_ARGS=--accept-license \
  -e SPLUNK_PASSWORD=helloworld \
  -e SPLUNK_ROLE=splunk_deployment_server \
  -e SPLUNK_APPS_URL=https://url/splunk-apps/app1.tgz,https://url/splunk-apps/app2.tgz..... \
  -p 8000:8000 \
  -p 8089:8089 \
  -v default.yml:/tmp/defaults/default.yml  splunk/splunk:7.2.5 start
```

The issue I come across with this (we actually haver about 50 apps we install, all custom stuff we wrote) is that it installs EVERY app on the deployment server, which TBH really confuses the server since they are intended to be installed on specific hosts defined by the server classes.

Looking at the ansible, it runs
```# TODO: Might be better to use synchronize here, but we'll need rsync installed
- name: Copy installed apps to deployment-apps
  command: "cp -R {{ splunk.app_paths.default }}/{{ item }} {{ splunk.app_paths.deployment }}"
  register: copy_apps
  changed_when: copy_apps.rc == 0
  failed_when: copy_apps.rc != 0
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ installed_apps }}"
```

Which makes sense, since that's what I'm seeing.. but I *think* in a deployment server role, it would make more sense to either apply the SPLUNK_APPS_URL directly to the deployment dir, OR move them to the deployment dir.  That way you don't end up installing all your apps on the deployment server, and thus turning it into 100's of different roles.

**Comment by sharkannon** [comment] 2019-04-12 22:43
Note: I could always create a deployment server image based on the splunk:7.2.5 image and copy the apps directly to /opt/splunk/etc/deployment-apps, but I'm trying to avoid running multiple copies of the image (if I can avoid it)

**Comment by nwang92** [comment] 2019-04-17 16:32
Hey @sharkannon, sorry for the delayed response! 

I believe the full installation (into etc/apps/) is done primarily because some apps are actually bundles that install more apps, and thus must be installed through special through specific endpoints or processes (think ITSI or ESS). However, the majority of apps can simply be untarred into a specific directory and will work as intended.

In order to support both, I guess the best course of action would be for the deployment server to also uninstall the apps from itself after they get copied?

As an aside, I'm also wondering if the deployment server fits your use-case with running Splunk on Docker? We mainly added that role to support the matrix of splunk roles, but you could also get away with passing `SPLUNK_APPS_URL` into each class of containers so designate which apps go on indexers, search heads, etc. That's mostly a thought-experiment of mine since the use of the deployment server might not be as valuable in the context of managing a fleet of containers vs. a fleet of VMs.

**Comment by sharkannon** [comment] 2019-04-17 22:36
Well a deployment server is used to mostly manage which apps go on FORWARDERS (CM/Deployer is used for indexers and other items).  We have hundreds of forwarders that all have to check in to the deployment server.

TBH things are working well (we're running 7.2.3),. but I'm using the Legacy splunk docker setup, since I started doing all of this on 7.0.3 and have just modified the image everything above.  I thought it was about time to actually start using your new style, with ansible.

So yea, the SPLUNK_APPS_URL won't work with the shear volume of hosts that are configured by the deployment server.

The other option I have, which is just what I was trying to avoid, is  I can pull in and create my own "deployment server image" which is just a copy of splunk/splunk:latest but adds the apps to /opt/splunk/etc/apps

That way does work, but it means I have to maintain multiple splunk images, which is what I was HOPING to avoid (Hoping to be able to just use the default.yml and other settings to manage the full infra.

**Comment by sharkannon** [comment] 2019-04-17 22:39
> In order to support both, I guess the best course of action would be for the deployment server to also uninstall the apps from itself after they get copied?

that would work, but wouldn't that kinda be inefficient? 

I think that if you're setting up a deployment server, you should already KNOW the dependencies and include them yourself.

So basically have a second variable, only for the deployment_server role.. SPLUNK_DEPLOY_APPS_URL or the like.. should probably follow a simple untar process to the deployment-apps directory.

**Comment by sharkannon** [comment] 2019-04-24 17:27
Actually digging into this ever further, the deployment_)server role is actually kinda dangerous, or at least that's how it appears.

```---
- name: Define all serverClass
  ini_file:
    path: "{{ splunk.home }}/etc/system/local/serverclass.conf"
    section: "serverClass:all"
    option: whitelist.0
    value: "*"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"

- name: Define all:app serverClass
  ini_file:
    path: "{{ splunk.home }}/etc/system/local/serverclass.conf"
    section: "serverClass:all:app:*"
    option: restartSplunkd
    value: "true"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    allow_no_value: true```

basically enables ALL deployed apps on all servers talking to the deploymentServer.. that kinda defeats the purpose of the deployment server completely.

**Comment by sharkannon** [comment] 2019-04-24 18:41
I might see what I can do to come up with a PR to help solve this, but I am not so sure that the deployment_server role works in a Splunk Enterprise environment.

**Comment by lephino** [comment] 2019-04-24 19:37
To the last 2 comments, to explain more, this repo is designed to be at creation, if you specified apps, install them on the DS, and then push them to any forwarders you specified.  Since this was a generic first pass for the app install, we simply push all the apps you specified to all DS hosts, expecting that you'd modify this later in the DS via the gui.  It's impossible to guess every configuration, but would love to hear some thoughts on what you guys would like to see for "app support" and any ideas on configuration syntax.

**Comment by sharkannon** [comment] 2019-04-24 19:52
Sorry, I probably came across wrong, I’m sorry.

The idea I saw with this is that we try to store our config and they like in config maps and the like so that other than the data (vars) the containers would be immutable and easily redeplyable. We have this running in Kubernetes with only the search head and indexers with persistent data mounts.

**Comment by sharkannon** [comment] 2019-04-24 20:15
Sorry, I may have come across a little wrong.. I had some of my stuff wiped out on our dev environment (I was able to recover, but it kinda shocked me), so reacted a little strongly.

I understand that this is for "initial" setup, but does this not get run every time you redeploy the DS? On an Upgrade or you just have a failure?  So if you deleted this section because that's not how you wanted it, it would just end up adding it back and thus cause all your apps to get deployed again.

**Comment by sharkannon** [comment] 2019-04-24 20:19
(I currently have a splunk infra running in production in GKE using the splunk-legacy docker setup, and was trying to upgrade to this new infra)

**Comment by lephino** [comment] 2019-04-24 20:34
Yeah we should add a "generate_ds_classes" flag as an environment var.  I think it should be optional and someone may actually want the "all".

**Comment by sharkannon** [comment] 2019-04-24 20:36
Yea... I have a couple ideas I might try to get into code.. they are kinda rough atm (and I'm not that great with ansible).  I just have to think about it a bit more, but in my infra I try to keep things as immutable as possible so that if we lost the environment, we could recover it/reproduce it again with minimal effort (aka no manual intervention, though we may have lost ALL the data).

**Comment by lephino** [comment] 2019-04-24 20:43
in your specific usecase, I think if we just get the env flag for ignoring that play, and then you use the "confs" yaml syntax (https://github.com/splunk/docker-splunk/blob/develop/docs/ADVANCED.md#create-custom-configs), you could accomplish everything you're after.  There's another issue open about doing app installs (https://github.com/splunk/splunk-ansible/issues/35), and I want to eventually expose a way to specify what directories you can install to (like deployment_server, or cluster_master/master apps or SHC/deployment-apps).  I picture something will be like the confs endpoint, except we'll have an "apps" endpoint, and you can have sections for where you want something installed, and the install style (untar vs apps rest endpoint) and would have support for all the SVA roles.

**Comment by sharkannon** [comment] 2019-04-24 20:44
The "custom configs" might be a challenge.. we have ~150 different server types and configs.. I might have to write a converter from INI -> yaml format, not a big deal.

**Comment by sharkannon** [comment] 2019-04-24 20:45
Though having a "default" + "role specific" config file would be another nice feature.. defaults that are shared, and role specific configs for other things.

**Comment by nwang92** [comment] 2019-04-24 21:04
> So yea, the SPLUNK_APPS_URL won't work with the shear volume of hosts that are configured by the deployment server.

The workflow I was thinking was more-on-the-lines of removing the dependency on the deployment server altogether. For instance:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forwarder-group-1 
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: uf
          image: splunk/universalforwarder:latest
          env:
            - name: SPLUNK_PASSWORD
              value: helloworld
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_APPS_URL
              value: "http://web/appA.tgz,http://web/appB.tgz"
          ports:
            - name: hec-input
              containerPort: 8088
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forwarder-group-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: uf
          image: splunk/universalforwarder:latest
          env:
            - name: SPLUNK_PASSWORD
              value: helloworld
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_APPS_URL
              value: "http://web/appC.tgz,http://web/appD.tgz"
          ports:
            - name: hec-input
              containerPort: 8088
```

Alternatively, because the containers are "cheap" I actually envisioned and documented some workflows that involved bringing up multiple deployment servers managing subsets of your forwarders - see [here](https://splunk.github.io/docker-splunk/advanced/DEPLOYMENT_SERVER.html#role-based-distribution).

But in general, there are some gaps between the use of the deployment server in non-containerized infrastructure vs containerized. Particular around actually defining the serverclass.conf, the categorization of classes by IP/hostname is not as straightforward when they're dynamically and sometimes randomly created?

**Comment by sharkannon** [comment] 2019-04-24 21:06
hostnames aren't that big of a deal if you use regex and the like and have a standard naming convention.  we use ${app}-${region}-${env}-whateveryouwant standard and regex parse that for deployments and the like...

you're option doesn't really work in a large distributed environment with 100's of different types of forwarders and apps, or at least it's not easily maintainable.

**Comment by sharkannon** [comment] 2019-05-22 20:48
Interesting changes, will have to experiment with them.

**Comment by nwang92** [comment] 2019-06-05 17:10
I'm gonna close this issue as relevant code changes are merged and we just pushed out new images. However, please feel free to re-open or add comments here if you want to continue the conversation or give us additional feedback!

**Closed by nwang92** 2019-06-05 17:10 UTC
