### ISSUE TITLE
Looks like setting splunkbase_username and splunkbase_password breaks the ansible playbook build

### ISSUE THREAD

**Issue by nickychow** [splunk/splunk-ansible#271] opened 2019-10-03 07:13 UTC
Hey, 

when I was trying to setup Splunk Heavyweight Forwarder by using the latest Docker image `splunk/splunk:7.3.1`.  I found the ansible playbook failed to finish every time I set `splunkbase_username` and `splunkbase_password`. 

Here are the errors:

```
ansible-playbook 2.8.5
  config file = /opt/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/library', u'/opt/ansible/apps/library', u'/opt/ansible/ansible_commands']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
Traceback (most recent call last):
  File "inventory/environ.py", line 445, in <module>
    main()
  File "inventory/environ.py", line 431, in main
    getSplunkInventory(inventory)
  File "inventory/environ.py", line 85, in getSplunkInventory
    inventory["all"]["vars"] = getDefaultVars()
  File "inventory/environ.py", line 151, in getDefaultVars
    getSplunkApps(defaultVars)
  File "inventory/environ.py", line 168, in getSplunkApps
    response = urllib2_parse.urlopen("https://splunkbase.splunk.com/api/account:login/", "username={}&password={}".format(splunkbase_username, splunkbase_password))
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlopen'
ERROR: Couldn't read "/opt/splunk/etc/splunk-launch.conf" -- maybe $SPLUNK_HOME or $SPLUNK_ETC is set wrong?                                                                                                                                                                    
```

It looks like the lib used for this `urllib2_parse` has been changed.

**Comment by nwang92** [comment] 2019-10-03 15:45
This should be a duplicate of https://github.com/splunk/docker-splunk/issues/241 and fixed by https://github.com/splunk/splunk-ansible/pull/265.

Can you try using the `splunk/splunk:7.3.2` image and see if that resolves the issue?

**Closed** 2019-10-14 16:46 UTC
